### ISSUE TITLE
Add tests for public access

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-tests#11]
Other than the WAC-Allow tests, all tests test what happens when Bob accesses a resource that Alice gave him some level(s) of access to.

We should add tests where:
- an unauthenticated user tries to access a resource (see https://github.com/solid/web-access-control-spec#public-access-all-agents)
- a random authenticated user tries to access a resource (see https://github.com/solid/web-access-control-spec#authenticated-agents-anyone-logged-on)

Maybe just copy `read.test.ts` and change that so that it tests those two situations.

**Comment by bourgeoa** [comment]
PR #28
