### ISSUE TITLE
Add test for empty ACL doc

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-tests#29]
What should happen if an ACL doc exists but contains no triples? I think it should be interpreted as "nobody has access", but would be good to have a test for this and see how the different implementations behave in this case.

**Comment by csarven** [comment]
Indeed no access.

**Comment by bourgeoa** [comment]
@michielbdejong where do you want the test to be located ? is It in read.test.ts

**Comment by michielbdejong** [comment]
Maybe add it to https://github.com/solid/web-access-control-tests/blob/master/test/surface/acl-doc-application.test.ts

**Comment by bourgeoa** [comment]
@michielbdejong
Yes it is interpreted as  'nobody as access' but : `You broke your server`
I think we cannot test this situation because you lose access to that part of the server and cannot delete the void acl.

We could come back to this one if/when a default owner will have all accesses.

**Comment by michielbdejong** [comment]
Ah yes, good point... 
OK, so this situation could occur, but if it does, then you can never get back out of it. So it's hard for us to write tests for this that clean up after themselves. OK, well let's park this then until we find some other approach to it.
